baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "viggy"

[ menu ]
  [[ menu.main ]]
    name = "About"
    url = "/about"
    weight = 1
  [[ menu.main ]]
    name = "Posts"
    url = "/posts"
    weight = 2
  [[ menu.main ]]
    name = "Contact"
    url = "/contact"
    weight = 3
