baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "viggy"

[ menu ]
  [[ menu.main ]]
  name = "Home"
  url = "/"
  weight = 1
  [[ menu.main ]]
  name = "All Posts"
  url = "/posts"
  weight = 2